### ISSUE TITLE
本地测试如何进行

### ISSUE THREAD

**Issue by mofhu** [csufuyi/niubility#5]
Hi Niubility,

早上看到你们连发了n个issue， 路过有个问题想请教：
你们开发时，本地测试是如何进行的？
部署到微信公众号的内容时刻要考虑服务，似乎不适合直接用于测试。

你们是本地进行测试吗？还是用另外的公众号专门测试，通过后再放到用户的公众号？
如果Fork代码，最简测试环境如何搭建？

**Comment by csufuyi** [comment]
如果只是测试应答逻辑，就是回应微信的post消息，可以用test.py在本地测试。
目前用sae的不同版本来区分，版本1正式对外，版本2测试新功能。另外用个测试的公众号连接测试版本。

**Comment by mofhu** [comment]
thx :)
